### ISSUE TITLE
div II feedback

### ISSUE THREAD

**Issue by mariumtapal** [sds270-s22/ftirsr#12]
looking at last commit [43bf979](https://github.com/sds270-s22/plsr/commit/43bf979276d3ab74cc950aef94e607e111648629)

1. Passes `install_github`: ✅
2. Documentation builds: ✅
3. Passes R CMD check: ✅

`0 errors ✓ | 0 warnings ✓ | 0 notes ✓`

@beanumber

**Comment by beanumber** [comment]
One potential solution to your data storage and documentation problems would be to store the data in tidy form as two long tables. So, `greenland_sites` would be a 28 x 2 tibble with variables `sample_id` and `bsi_percent`, and then `greenland_wavenumber` would be a 3698 x 2 tibble with variables `sample_id` and `wavenumber`. Then your data is tidy, and you only have to document three variables (which is all you have). 

Better yet, you could call the smaller table `sites` and include the data from Alaska and wherever else as well. Then the big table would be `greenland`, and when you add Alaska, it would just be another big table called `alaska`.
