### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by hartlegr** [sds270-s22/ftirsr#3]
I think we should change the package name to be something a little more unique from 'pls' (another existing package) and to be a more accurate description of what we are actually doing. this will mean at least: 
- changing the name in the description
- changing the name of the project (locally)
- changing the name of the folder (locally)
- changing the name of the github repo 
- changing the name in every other place within the package (places it's loaded, etc)

**Comment by hartlegr** [comment]
This is low priority/something to do towards the end

**Comment by beanumber** [comment]
Actually, [plsr](https://cran.r-project.org/web/packages/plsr/index.html) is already a package on CRAN, so you will have to change your package name to something else. I would do this sooner, rather than later, to avoid confusion.
